In [1]:
import numpy as np

In [2]:
arr1=np.array([1,3,2,4,9,])
arr2=np.zeros(5)
arr3=np.ones(3)
print(arr1)
print(arr2)
print(arr3)

[1 3 2 4 9]
[0. 0. 0. 0. 0.]
[1. 1. 1.]


In [3]:
arr4=np.concatenate([arr1,arr2,arr3])
arr4

array([1., 3., 2., 4., 9., 0., 0., 0., 0., 0., 1., 1., 1.])

In [4]:
print(arr1.sort())
arr1

None


array([1, 2, 3, 4, 9])

In [5]:
print(arr1[2])
arr1[-3]

3


np.int64(3)

In [6]:
print(arr1[1:4])
arr1[slice(1,4)]

[2 3 4]


array([2, 3, 4])

In [7]:
arr1+arr2

array([1., 2., 3., 4., 9.])

In [12]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())
arr1.mean()

9
1
19
3.8


np.float64(3.8)

In [16]:
arr1[(arr1<5)&(arr1>2)]

array([3, 4])