In [18]:
import torch
import numpy as np
torch.__version__

'2.0.0+cu118'

In [5]:
x=torch.empty(5,3)
x

tensor([[9.2755e-39, 1.0561e-38, 6.0613e-39],
        [1.0194e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39]])

In [8]:
y=torch.rand(5,3)
y

tensor([[0.3332, 0.2738, 0.0597],
        [0.2515, 0.8823, 0.1748],
        [0.2476, 0.0026, 0.9726],
        [0.9074, 0.2539, 0.5713],
        [0.5043, 0.1860, 0.2677]])

In [9]:
x+y

tensor([[1.2691, 0.9798, 0.6615],
        [0.4707, 1.3425, 0.7630],
        [0.6112, 0.6381, 1.6270],
        [1.7351, 0.2592, 0.8271],
        [1.2734, 0.7956, 0.6180]])

In [11]:
a=torch.ones(5)
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1,8)
print(x. size(),y. size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [10]:
x[:,1]

tensor([0.7061, 0.4602, 0.6355, 0.0053, 0.6097])

In [19]:
a=np.ones(5)
b=torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)